#!/bin/bash
set -e
# set -x #echo on

ADB=${ADB:-adb}
VLC=${VLC:-/Applications/VLC.app/Contents/MacOS/VLC}
SNDCPY_APK=${SNDCPY_APK:-"$(dirname "$0")"/sndcpy.apk}
SNDCPY_PORT=${SNDCPY_PORT:-28200}

ADBS=${ADBS:-"$(dirname "$0")"/android-select-device}

serial=$($ADBS)

"$ADB" $serial install -t -r -g "$SNDCPY_APK" ||
{
    echo 'Uninstalling existing version first...'
    "$ADB" $serial uninstall com.rom1v.sndcpy
    "$ADB" $serial install -t -g "$SNDCPY_APK"
}

"$ADB" $serial forward tcp:$SNDCPY_PORT localabstract:sndcpy
"$ADB" $serial shell am start com.rom1v.sndcpy/.MainActivity
sleep 1s

activityName=$($ADB $serial shell dumpsys activity activities | grep mResumedActivity | cut -d . -f 5 | cut -d ' ' -f 1)

while [[ $activityName -eq "MediaProjectionPermissionActivity" ]]
do
    if [ "$activityName" != "MediaProjectionPermissionActivity" ]
    then
        break
    fi
    $ADB $serial shell input keyevent 22
    $ADB $serial shell input keyevent 22
    $ADB $serial shell input keyevent 66
    activityName=$($ADB $serial shell dumpsys activity activities | grep mResumedActivity | cut -d . -f 5 | cut -d ' ' -f 1)
done

$ADB $serial shell input keyevent 164

"$VLC" -Idummy --demux rawaud --network-caching=50 --play-and-exit tcp://localhost:"$SNDCPY_PORT"

$ADB $serial shell input keyevent 164
